webse/forward_home/routes.py
from flask import render_template, url_for, Blueprint
from webse import application, db
forward_home= Blueprint('forward_home', __name__)


@forward_home.route('/home')
@forward_home.route('/')
def home():
    db.create_all()
    return render_template('forward_home/home.html', title='Home')

@forward_home.route('/developers')
def developers():
    return render_template('forward_home/developers.html', title='Developers')

  

webse/forward_users/routes.py
from flask import render_template, url_for, Blueprint, flash, redirect, request
from webse import application, db, bcrypt
from webse.forward_users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from webse.models import User
from flask_login import login_user, current_user, logout_user, login_required
from webse.forward_users.utils import save_picture, read_image

forward_users= Blueprint('forward_users', __name__)

@forward_users.route('/forward/register', methods=['GET','POST'])
def forward_users_register():
    if current_user.is_authenticated:
        return redirect(url_for('forward_home.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=user_hashed_password, institution=form.institution.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! Now, you are able to login!', 'success')
        return redirect(url_for('forward_users.forward_users_login'))
    return render_template('forward_home/forward_register.html', title='Register', form=form)

@forward_users.route('/forward/login', methods=['GET','POST'])
def forward_users_login():
    if current_user.is_authenticated:
        return redirect(url_for('forward_home.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You have logged in! Now, you can start to use Forward!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('forward_home.home'))
        else:
            flash('Login Unsuccessful. Please check email and password!', 'danger')   
    return render_template('forward_home/forward_login.html', title='Login', form=form)       

@forward_users.route('/forward/logout')
def forward_users_logout():    
    logout_user()
    return redirect(url_for('forward_home.home'))

@forward_users.route('/forward/account', methods=['GET','POST'])
@login_required
def forward_users_account(): 
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.institution = form.institution.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('forward_users.forward_users_account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    encoded_data=read_image(current_user.image_file)

    return render_template('forward_home/forward_account.html', title='Account', image_file=encoded_data, form=form)   

webse/gd_course_chats/routes.py
from flask import render_template, url_for, Blueprint, flash, redirect, request
from webse import application, db, bcrypt
from webse.models import User, ChatGD
from flask_login import login_user, current_user, logout_user, login_required
from webse.forward_users.utils import read_image
from webse.gd_course_chats.forms import ChatForm

gd_course_chats= Blueprint('gd_course_chats', __name__)

@gd_course_chats.route('/green_digitalization_course/create_chat', methods=['GET', 'POST'])
@login_required
def gd_course_chats_create_chat(): 
    return render_template('gd_course/gd_chats/gd_course_create_chat_home.html', title='Create Chat Home')

@gd_course_chats.route('/green_digitalization_course/view_chat', methods=['GET', 'POST'])
@login_required
def gd_course_chats_view_chat(): 
    return render_template('gd_course/gd_chats/gd_course_view_chat_home.html', title='View Chat Home')

# These routes are specific for each chat (create-chat)
@gd_course_chats.route('/green_digitalization_course/main_chat/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_main_chat(): 
    form = ChatForm()
    legend ='Create chat (main chat)'
    title = 'Create chat (main chat)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='none', chapter='none', group='main_chat')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)

    #HVL
@gd_course_chats.route('/green_digitalization_course/chat_HVL_g1/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g1_chat(): 
    form = ChatForm()
    legend ='Create chat group 1 (HVL)'
    title = 'Create chat group 1 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 1')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g2/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g2_chat(): 
    form = ChatForm()
    legend ='Create chat group 2 (HVL)'
    title = 'Create chat group 2 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 2')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g3/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g3_chat(): 
    form = ChatForm()
    legend ='Create chat group 3 (HVL)'
    title = 'Create chat group 3 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 3')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)    

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g4/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g4_chat(): 
    form = ChatForm()
    legend ='Create chat group 4 (HVL)'
    title = 'Create chat group 4 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 4')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)       

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g5/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g5_chat(): 
    form = ChatForm()
    legend ='Create chat group 5 (HVL)'
    title = 'Create chat group 5 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 5')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)  

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g6/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g6_chat(): 
    form = ChatForm()
    legend ='Create chat group 6 (HVL)'
    title = 'Create chat group 6 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 6')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)   

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g7/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g7_chat(): 
    form = ChatForm()
    legend ='Create chat group 7 (HVL)'
    title = 'Create chat group 7 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 7')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)  

@gd_course_chats.route('/green_digitalization_course/chat_HVL_g8/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_HVL_g8_chat(): 
    form = ChatForm()
    legend ='Create chat group 8 (HVL)'
    title = 'Create chat group 8 (HVL)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='HVL', chapter='none', group='group 8')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)     

        #NHH
@gd_course_chats.route('/green_digitalization_course/chat_NHH_g1/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_NHH_g1_chat(): 
    form = ChatForm()
    legend ='Create chat group 1 (NHH)'
    title = 'Create chat group 1 (NHH)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='NHH', chapter='none', group='group 1')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)

@gd_course_chats.route('/green_digitalization_course/chat_NHH_g2/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_NHH_g2_chat(): 
    form = ChatForm()
    legend ='Create chat group 2 (NHH)'
    title = 'Create chat group 2 (NHH)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='NHH', chapter='none', group='group 2')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)

@gd_course_chats.route('/green_digitalization_course/chat_NHH_g3/new', methods=['GET', 'POST'])
@login_required
def gd_course_chats_new_NHH_g3_chat(): 
    form = ChatForm()
    legend ='Create chat group 3 (NHH)'
    title = 'Create chat group 3 (NHH)'
    if form.validate_on_submit():
        chat = ChatGD(title=form.title.data, content=form.content.data, author=current_user, institution='NHH', chapter='none', group='group 3')
        db.session.add(chat)
        db.session.commit()
        flash('Your chat has been created!', 'success')
        return redirect(url_for('gd_course.gd_course_home'))
    return render_template('gd_course/gd_chats/gd_course_create_chat.html', title=title, form=form, legend=legend)    

@gd_course_chats.route('/green_digitalization_course/chat_NHH_g4/new', methods=['GET', 'POST'])
@login_required

webse/sbm_course_home/routes.py
from flask import render_template, url_for, Blueprint, request
from webse import application, db, bcrypt
from webse.models import AnnouncementGD
from webse.forward_users.utils import save_picture, read_image
sbm_course= Blueprint('sbm_course', __name__)

@sbm_course.route('/sustainable_business_models_course')
def sbm_course_home():
    page = request.args.get('page', 1, type=int)
    announcements = AnnouncementGD.query.order_by(AnnouncementGD.date_posted.desc()).\
        filter((AnnouncementGD.user_id==172) | (AnnouncementGD.user_id==173)).paginate(page=page, per_page=1)
    return render_template('sbm_course/sbm_course_home.html', announcements=announcements, title='Sustainable Business Models Course', func=read_image)

@sbm_course.route('/sustainable_business_models_course/app_module')
def sbm_course_app_module():
    return render_template('sbm_course/sbm_app_module/app_module_home.html', title='Sustainable Business Models Course, App Module')
  
#Chapter 8
@sbm_course.route('/sustainable_business_models_course/app_module/chapter8')
def sbm_course_chapters_ch8(): 
    return render_template('sbm_course/sbm_app_module/chapters/ch8.html', title='Sustainable Business Models Course, ch8')   

#Chapter 9
@sbm_course.route('/sustainable_business_models_course/app_module/chapter9')
def sbm_course_chapters_ch9(): 
    return render_template('sbm_course/sbm_app_module/chapters/ch9.html', title='Sustainable Business Models Course, ch9') 

#Chapter 10
@sbm_course.route('/sustainable_business_models_course/app_module/chapter10')
def sbm_course_chapters_ch10(): 
    return render_template('sbm_course/sbm_app_module/chapters/ch10.html', title='Sustainable Business Models Course, ch10') 
  

webse/templates/gd_course/gd_course_layout.html
<html>
    <head>

        <!--Import Google Roboto style:-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400&display=swap" rel="stylesheet">

        <!--Import the Bootstrap CSS file:-->
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
        />

        <!--For the plots-->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

        <!--Import the FullCalendar js and CSS file:-->
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css">

        <!-- Import Font Awesome CDN. It does not work-->
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

        <!-- Import Font Awesome. My own KIT-->
        <script src="https://kit.fontawesome.com/b6331c8bf2.js" crossorigin="anonymous"></script>

        <!--Import the CSS file with the style:-->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_layout.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_home.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_register.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_account.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_chat.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_app_calculator.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_questionnaire.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_chapters.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_statistics.css') }}">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='gd_course_chapters_ch3.css') }}">

        <!-- To activate media queries -->
        <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

        <!-- To use  highlightjs.org and type code inside HTML -->
        <link rel="stylesheet" href="/path/to/styles/default.min.css">

        <!-- Matjax -->
        <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>


        {% if title %}
            <title>Forward - {{ title }}</title>
        {% else %}
            <title>Forward</title>
        {% endif %}


    </head>
    <body>        
        <nav class="navbar">
            <div class="container"> <!--class="container_layout"-->
                <div class="menu_left">
                    <div class="logo">
                        <a href="{{ url_for('forward_home.home') }}"><img
                            src="{{url_for('static', filename='figures/forward/forward_icon.svg')}}"
                            width="50" 
                            height="50"
                        alt=""/></a>
                        <a href="{{ url_for('gd_course.gd_course_home') }}"><img
                            src="{{url_for('static', filename='figures/forward/gd_course_icon.svg')}}"
                            width="50" 
                            height="50"
                        alt=""/></a>
                        <a href="{{ url_for('sbm_course.sbm_course_app_module') }}"><img
                            src="{{url_for('static', filename='figures/sustainable_business_models/app_development_module/app_development_module_home_only_icon.svg')}}"
                            width="50" 
                            height="50"
                        alt=""/></a>
                    </div>
                    <div class="menu">
                        {% if current_user.is_authenticated %}
                            {% if current_user.email=='admin@demo.com' %}
                                <ul class="nav">
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_announcements.gd_course_announcements_new_announcement') }}">Announcement</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chats.gd_course_chats_create_chat') }}">Create-Chat</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chats.gd_course_chats_view_chat') }}">View-Chats</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_statistics.statistics') }}">Statistics</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_students_apps.gd_students_apps_home') }}">Students-apps</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_app_calculator.app_calculator_entry') }}">Carbon-app</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chapters.gd_course_chapters_haugesund') }}">Haugesund</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('forward_users.forward_users_logout') }}">Logout</a>
                                    </li>
                                </ul>
                            {% else %}
                                <ul class="nav">
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chats.gd_course_chats_create_chat') }}">Create-Chat</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chats.gd_course_chats_view_chat') }}">View-Chats</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_statistics.statistics') }}">Statistics</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_students_apps.gd_students_apps_home') }}">Students-apps</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_app_calculator.app_calculator_entry') }}">Carbon-app</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('gd_course_chapters.gd_course_chapters_haugesund') }}">Haugesund</a> 
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('forward_users.forward_users_logout') }}">Logout</a>
                                    </li>
                                </ul>
                            {% endif %} 
                        {% else %}
                        <ul class="nav">
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_chats.gd_course_chats_create_chat') }}">Create-Chat</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_chats.gd_course_chats_view_chat') }}">View-Chats</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_statistics.statistics') }}">Statistics</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_students_apps.gd_students_apps_home') }}">Students-apps</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_app_calculator.app_calculator_entry') }}">Carbon-app</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('gd_course_chapters.gd_course_chapters_haugesund') }}">Haugesund</a> 
                            </li>
                            <li class="nav-item">
                                <a href="{{url_for('forward_users.forward_users_login')}}">Login</a> 
                            </li>
                        </ul>
                        {% endif %}    
                    </div>                    
                </div>
                <!-- <div class="menu_right">
                    <ul class="nav">
                        <li class="nav-item">
                            <a href="#">Students-apps</a>
                        </li>
                        <li class="nav-item">
                            <a href="#">Students-thesis</a>
                        </li>
                        <li class="nav-item">
                            <a href="#">Research</a>
                        </li>
                        <li class="nav-item">
                            <a href="#">Collaborators</a>
                        </li>
                    </ul>
                </div> -->
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>
            </div>
        </nav>


    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="footer">
        <div class="container">  
            <div class="item">
                <p class="lead">
                Green Digitalization Course
                </p> 
            </div>              
            <div class="item">
                <a href="#">
                    <i class="bi bi-arrow-up-circle h1"></i>
                </a>
            </div> 
        </div>
    </footer>


    <!--Menu JavaScript-->
    <script src="static/forward_home_main.js"></script>

    <!-- To use  highlightjs.org and type code inside HTML -->
    <script src="/path/to/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
     

    <!-- Question Accordion -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    </body>
</html>

